### PR TITLE
adding better transfer filter and removing duplicated settings

### PR DESCRIPTION
**Pull request by Kongolan**
I did add a new trash indicator, which is basically cp * (iv / 100), which is now used for pokemon comparison. This will replace the PrioritizeIVOverCPoption.

- new option to set minimum CP to keep even when they have good IV
- adding new trash indicator
- remove unused options (PrioritizeIVOverCP, boolean options for transfer keep "0" is now off)
- keeping only 1 duplicated pokemon with best trash indicator
- own xml config for iv and minimum cp per pokemonId, else they keep default
- formula now has a factor (0 = only iv will be considered, 1 = cp and iv equally) -> cp^factor * (iv / 100)

Hope you can take a look at it.

### CODE REVIEW

**Comment by killercloud** [comment]
Hi @Kongolan ,
I think it would be better if you add a parameter where you can define a factor to apply to the CP part of the formula. We can have the following case:
        - 450CP 90%IV
        - 1000CP 40%IV
In the previous case, i want to keep the 1000 CP one (because i dont want to expend a lot of dust in the 450CP pokemon). This way everybody could configure it as they want.

Maybe the formula could look like:
      
 (iv / 100) * cp^factor
--> where factor is a value less than 1 (priorice IV), 1 (no priorization) or greater than 1 (priorice CP).

Regards,

**Comment by Kongolan** [comment]
Actually this is pretty smart, sure i can add it.

**Comment by Kongolan** [comment]
doesn't seem like i have something else to add, if you have more feature requests send me.

**Comment by killercloud** [comment]
Hi @Kongolan,

Good job! hope @Spegeli include it in the public version soon.
I have also implemented another functionality to print the current inventory every 5 pokestops (when the bot recicle items). I can send you the code so you can create a new pull request if you want.

Regards!

**Comment by Kongolan** [comment]
It's not hard to add a inventory print after recycling^^

**Pull request closed without merging**
