### PR TITLE
Add random walking speed, with settings and console logging, random elevation with min/max increase/decrease, random throws and types of throw, random hit/miss pokemon

### PR DESCRIPTION
**Pull request by tperalta82**
This might be harder to detect than having a current fixed speed.

Currently running it with no issues.

### CODE REVIEW

**Comment by wowsuchdeveloper** [comment]
Issue #376

**Comment by wowsuchdeveloper** [comment]
Issue #380

**Comment by wowsuchdeveloper** [comment]
MakeMeHuman flag could also be used for #379 and #382.

**Comment by tperalta82** [comment]
You're totally right x) let's hope this is accepted

**Comment by Kongolan** [comment]
Still after all my research, speed is not a factor at all for any sort of bans. Accounts with 20km/h, 7km/h and 320km/h all got softban after reaching enough pokestops/d, pokemons_caught/d or exp/d. There are 100% other variables, going slower just let's your reach these variables slower.

**Comment by tperalta82** [comment]
Will take a look at kongolan suggestion

**Comment by Kongolan** [comment]
Well once again you modify the API classes :D you should not do that... RequestBuilder is really crucial.

**Comment by tperalta82** [comment]
This time i had no option, it replaces encrypt.dll with a managed code
port. Also, the encrypt.dll was being pinvoked in the request builder as
well

**Comment by johnnytavo** [comment]
The pull request works locally. I would suggest some instructions to resolve the PokemonGoEncryptSharp dependency.

**Comment by tperalta82** [comment]
I will not supply the binary due to legal issues, but you can build the DLL from here:
https://github.com/zone117x/pokemongo-encrypt-sharp

And put the built dll onto the PokemonGo.RocketAPI Main folder

Then it will work after you rebuild, and it will be properly copied to the necessary location.

**Comment by tperalta82** [comment]
I will update the README on my fork with that info as soon as possible, maybe later or something.

**Comment by Maharaja18** [comment]
Hello! 
I think this story is really  awesome, you're gonna love it, please read it here  <http://tonia.playthekeyboard.com/e5uq/0>

Hugs, turek42

**Pull request closed without merging**
