### PR TITLE
Feature auto incubation

### PR DESCRIPTION
**Pull request by Kongolan**
Hello there,

i just coded an auto incubation feature, so the bot can finally handle eggs and incubators.

Features:
- Adds automatically unused eggs to incubators
- Logs egg progress after recycling
- New Setting if they should use the incubation or not
- New Setting if you only want to use the unlimited basic incubator
- Eggs under 5km walk distance won't be used by limited incubators
- Includes a small fix of gitignore as well, since you upload userfiles

Hope you can merge it into.

Kind Regards,
- Kongolan

### CODE REVIEW

**Comment by Kongolan** [comment]
Updated and tested with the newest Logic.cs and such. Added an IncubateTask class.

**Comment by minipouss83** [comment]
NEED IT ^^

**Comment by spoofjack** [comment]
Looks good but i would take your personal information off from your changes in settings :)

**Comment by Kongolan** [comment]
Do i have them in the settings? :D

**Comment by spoofjack** [comment]
Yes and I didnt know how to send private message.

Sent from Yahoo Mail on Android 
 
  On Wed, Aug 10, 2016 at 2:16 PM, Kongolan<notifications@github.com> wrote:   
Do i have them in the settings? :D

**Comment by Kongolan** [comment]
Did try to fix it and it messed up the changes, i might need to reopen this one here...

**Comment by Spegeli** [comment]
Added to the next Version ;-)

**Comment by Maharaja18** [comment]
Hi friend! 

I've had  a  really nice day and  I just  wanted to share something really cool  with  you, please take a look <http://suit.soundworksla.org/e5jg/641>

Wishes, turek42

**Pull request closed without merging**
