### PR TITLE
Issue 98

### PR DESCRIPTION
**Pull request by Shakazan**
Allow users to retain Max (x) number of Max CP pokemons as well as Max (Y) number of Max IV pokemons.

Added test project with some basic tests and refactored the Inventory.GetPokemonsToTransfer signature and ISettings so that we can inject it

### CODE REVIEW

**Comment by xuyu822** [comment]
Hi there, I am no coding expert at all, but my bot hasn't been running this afternoon, any ideas?

**Comment by gvjordan** [comment]
@xuyu822 There is a change with a recent update to the Pokemon GO API which broke all the things. It may take a little before it's reverse engineered again, check back later. :)

**Comment by somo1ful** [comment]
so apparently they now force you to download the newest version of PoGo and this bot doesn't find any pokestops no matter what's your MaxTravelDistanceInMeters. It works on bluestacks in the same location

**Comment by sonnax** [comment]
@Spegeli A big thank you for your work. I'm sure another working version will be up in no time.

**Comment by GhisM** [comment]
Hey guys,

Same as Xuyu, my my bot hasn't been running lately. 
It says that i have no Pokestops in my area, but the area is set on 3000 meters... Any ideas ? Is that a problem coming with the changes on thz PokeGO API ?

83fcd642b7b3606fc9731b3a92340b43

**Comment by gvjordan** [comment]
@GhisM There have been massive changes with the API, all bots are dead atm afaik. I'd check back at a different time :)

**Comment by xuyu822** [comment]
@gvjordan thank you for letting us know, and @Spegeli thank you for a great app! When you guys have a fix kindly let us know! =D

**Comment by gnrendrawijaya** [comment]
guys ,anyone have bot just auto transfer pokemon ?

**Comment by executor819** [comment]
bot nor working no... API pogo UPD

**Comment by Neo-San** [comment]
guys, please guide me to our starting position, i just want to know where i should look the second we walk

**Comment by mephistophaIes** [comment]
I think niantic updated their API and we have to wait new API and there is no new release for IOS or Android its still v0.31. How many days you need guys for reverse engineering?

**Comment by executor819** [comment]
Nope.. i think bot will die lol...

**Comment by Killmachine** [comment]
Why don't we have any news from the developers yet?

**Comment by Shakazan** [comment]
Because technically the developers of the game have introduced similar
technology that the banks use. There are private /public keys used now
which are going to be nearly impossible to crack unless we get some insider
information.

**Comment by fourmansyah** [comment]
Just Dont Use API From Google ...

**Comment by ughyme** [comment]
mine isnt working either, even after fix

image

**Comment by ughyme** [comment]
sorry that was a bit small
image

**Comment by drite121** [comment]
still error?
i try and encrypt.dll unable to load

**Pull request closed without merging**
